FROM oven/bun:1.3-alpine AS builder
WORKDIR /app

COPY . .
RUN bun install --frozen-lockfile --ignore-scripts

FROM oven/bun:1.3-alpine AS runner
WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/packages/tsconfig ./packages/tsconfig
COPY --from=builder /app/packages/api ./packages/api

WORKDIR /app/packages/api

ENV NODE_ENV=production
EXPOSE 3000

CMD ["bun", "run", "src/server.ts"]
